# Generated by Django 4.0.5 on 2022-06-07 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('user_type', models.CharField(choices=[('Doctor', 'Doctor'), ('Patient', 'Paitient')], max_length=100)),
                ('user_status', models.CharField(choices=[('Doctor', 'Doctor'), ('Patient', 'Paitient')], default=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paitient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('profile_picture_path', models.CharField(max_length=1000)),
                ('username', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.user')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('profile_picture_path', models.CharField(max_length=1000)),
                ('username', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.user')),
            ],
        ),
    ]
