# Generated by Django 4.0.5 on 2022-06-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_path',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='summary',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
