# Generated by Django 4.0.5 on 2022-06-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_blog_publish_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(max_length=50000, null=True),
        ),
    ]
