# Generated by Django 4.0.5 on 2022-06-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_blog_content_alter_blog_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
