# Generated by Django 4.0.5 on 2022-06-12 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_blog_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
    ]
