# Generated by Django 4.0.5 on 2022-06-12 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_blog_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='content',
            new_name='text',
        ),
    ]
