# Generated by Django 4.0.5 on 2022-06-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_rename_content_blog_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='text',
        ),
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
