# Generated by Django 4.0.5 on 2022-06-17 00:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_appointment_date'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='appointment',
            name='appointment_id',
            field=models.CharField(default="0", max_length=5, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
