# Generated by Django 4.0.5 on 2022-06-17 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_remove_appointment_id_appointment_appointment_id'),
    ]

    operations = [
       
    ]
