# Generated by Django 4.0.5 on 2022-06-17 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_remove_appointment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
